name: teachopencadd
channels:
  - samoturk
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - jupyter
  - rdkit>=2018.09.2.0
  - pymol
  - pmw
  - scikit-learn
  - biopandas
  - seaborn
  - pypdb
  - chembl_webresource_client
  - nglview
  - pytest-notebook
