name: teachopencadd
channels:
  - rdkit
  - samoturk
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - rdkit
  - pymol
  - pmw
  - scikit-learn
  - biopandas
  - seaborn
  - pypdb
  - chembl_webresource_client
