name: teachopencadd
channels:
  - conda-forge
  - defaults
  - openbabel
dependencies:
  - python>=3.6
  - pip
  - jupyter
  - jupyterlab
  - rdkit>=2018.09.2.0
  - pmw
  - scikit-learn
  - biopandas
  - seaborn
  - pypdb
  - chembl_webresource_client
  - nglview
  - pytest-notebook
  - requests
  - openbabel 2.4.1
  - lxml
  - bravado
  - beautifulsoup4
  - ipywidgets>=7.5
  - biotite
  - mdanalysis
  - pip:
      - suds-community
      - https://github.com/jaimergp/autodocktools-prepare-py3k/archive/master.zip
      - https://github.com/volkamerlab/superposer/archive/ce27e914f64b2025e969745f688e19989ff72e82.zip
    # Plip must be installed with --no-deps manually:
    # pip install --no-deps https://github.com/ssalentin/plip/archive/stable.zip

## For Jupyter lab extensions, run:
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
# jupyter labextension install nglview-js-widgets
