name: teachopencadd
channels:
  - conda-forge
  - defaults
  - openbabel
dependencies:
  - python>=3.6
  - pip
  - jupyter
  - jupyterlab
  - rdkit>=2018.09.2.0
  - pmw
  - scikit-learn
  - biopandas
  - seaborn
  - pypdb
  - chembl_webresource_client
  - nglview
  - requests
  - openbabel
  - lxml
  - bravado
  - beautifulsoup4
  - ipywidgets>=7.5
  - biotite
  - mdanalysis
  - plip
  - biopython 1.77
  # Workaround for https://github.com/computationalmodelling/nbval/issues/153
  - pytest 5.*
  - nbval
  - pip:
      - suds-community
      - https://github.com/jaimergp/autodocktools-prepare-py3k/archive/master.zip
      - https://github.com/volkamerlab/opencadd/archive/b6d9c511f89ff200c45532e614f1abffa35e2ab7.zip
## For Jupyter lab extensions, run:
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
# jupyter labextension install nglview-js-widgets
