name: ci

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "maintenance/.+"
  schedule:
    # Run a cron job once daily
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7]
    env:
      PYVER: ${{ matrix.python-version }}
      PACKAGE: teachopencadd  # Replace with the name of your package

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        channel-priority: true
        environment-file: environment.yml
        auto-activate-base: false

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info --all
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        PYTEST_ARGS=" --nbval"
        pytest $PYTEST_ARGS $PACKAGE

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true